name: Automation
on:
  push:
    branches: ["**"]
  release:
    types: [published]
  pull_request:
    branches: ["**"]
jobs:
  build:
    name: Build
    runs-on: "macos-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run ci:test
      - name: Publish
        if: github.event_name == 'release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
